---
title: "Untitled"
author: "Maximiliano Ros"
date: "16/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(formattable)
library(readr)
```

#ENERO
```{r}
enero1<-read.table("1_ENERO.csv",  sep = ";", dec = ".", header = TRUE,
           encoding = "UTF-8", stringsAsFactors = FALSE, quote = "")
enero1<- enero1 %>% mutate(semana=1)
enero2<-read.table("2_ENERO.csv",  sep = ";", dec = ".", header = TRUE,
           encoding = "UTF-8", stringsAsFactors = FALSE, quote = "")
enero2<- enero2 %>% mutate(semana=2)
enero3<-read.table("3_ENERO.csv",  sep = ";", dec = ".", header = TRUE,
           encoding = "UTF-8", stringsAsFactors = FALSE, quote = "")
enero3<- enero3 %>% mutate(semana=3,Rank=X.U.FEFF.Rank)
enero4<-read.table("4_ENERO.csv",  sep = ";", dec = ".", header = TRUE,
           encoding = "UTF-8", stringsAsFactors = FALSE, quote = "")
enero4<- enero4 %>% mutate(semana=4, Rank=X.U.FEFF.Rank)

enero<- bind_rows(enero1,enero2,enero3,enero4)
enero<- enero %>% group_by(Titulo,semana) %>% arrange(Titulo) %>% select(-c(Entradas.Total,X.U.FEFF.Rank))

rm(list=c("enero1","enero2","enero3","enero4"))
```




```{r}
enero_prueba<- enero %>% group_by(Titulo) %>% summarise(entradas_mes=sum(Espec..Semana), entradas_ult_semana=last(Espec..Semana),entradas_semama_anterio=lag(Espec..Semana), entradas_first_semana= first(Espec..Semana),semanas_total=max(Semana.Cartel),semanas_mes=sum(cantidad),pais, region,tipo, pantallas_max=max(Pantallas),pantallas_mes=sum(Pantallas), cantidad=1, mes="ENERO")
enero_prueba<-enero_prueba %>% summarise_all(last) %>% arrange(desc(entradas_mes))
#write.csv(enero_prueba, "enero_powerbi.csv")

enero_estrenos<-enero %>% filter(Semana.Cartel==1)
#write.csv(enero_estrenos, "enero_estrenos.csv")2
```

```{r}
#variaciones
variaciones_enero<-enero_prueba %>% summarise(Titulo, var_entradas_first_last=percent((entradas_ult_semana-entradas_first_semana)/entradas_first_semana), entradas_first_semana,entradas_ult_semana)
```




### FEBRERO ###
#### Del 03 de Febrero al 02 de Marzo. 

```{r}
febrero1<- read.csv("C:/Users/LENOVO/Documents/GitHub/EYD/reporte-mensual-cine-argentina/febrero/1.FEBRERO_02_09.csv", sep=";")
febrero2<- read.csv("C:/Users/LENOVO/Documents/GitHub/EYD/reporte-mensual-cine-argentina/febrero/2.FEBRERO_10_16.csv", sep=";")
febrero3<- read.csv("C:/Users/LENOVO/Documents/GitHub/EYD/reporte-mensual-cine-argentina/febrero/3.FEBRERO_17_23.csv", sep=";")
febrero4<- read.csv("C:/Users/LENOVO/Documents/GitHub/EYD/reporte-mensual-cine-argentina/febrero/4.FEBRERO_24_02.csv", sep=";")

febrero<- bind_rows(febrero1,febrero2,febrero3,febrero4) %>% mutate(cantidad=1)
rm(list = c("febrero1","febrero2","febrero3","febrero4"))
```

```{r}
febrero_datos<- febrero %>%  group_by(titulo) %>% summarise(entradas_mes=sum(Espec..Semana),      
                                                            entradas_ult_semana=last(Espec..Semana),
                                                            entradas_semama_anterio=lag(Espec..Semana), 
                                                            entradas_first_semana= first(Espec..Semana),
                                                            semanas_total=max(Semana.Cartel),
                                                            pantallas_max=max(Pantallas),
                                                            pantallas_mes=sum(Pantallas),
                                                            pantallas_ult_semana=last(Pantallas), 
                                                            pantallas_semana_anterior=lag(Pantallas), 
                                                            pantallas_first_semana=first(Pantallas),
                                                            semanas_mes=sum(cantidad),
                                                            pais, region,tipo,cantidad=1, mes="FEBRERO", Rank,
                                                            rank_mes=first(Rank),
                                                            rank_anterior=lag(Rank))

febrero_datos<-febrero_datos %>% summarise_all(last) %>% arrange(desc(entradas_mes))
febrero_datos<- febrero_datos %>% mutate(rank_total= 1:nrow(febrero_datos))
#write.csv(febrero_datos, "febrero_datos2.csv")


febrero_variaciones<- febrero_datos %>% mutate(
                      var_entradas_mensual=percent((entradas_ult_semana-entradas_first_semana)/entradas_first_semana),                                          
                      var_entradas_semana_previa=percent((entradas_ult_semana-entradas_semama_anterio)/entradas_semama_anterio),                                 
                      var_pantallas_mes=percent((pantallas_ult_semana-pantallas_first_semana)/pantallas_first_semana),
                      var_pantallas_semana_previa=percent((pantallas_ult_semana-pantallas_semana_anterior)/pantallas_semana_anterior), 
                      var_rank_mensual=(rank_mes-Rank), 
                      var_rank_ult_semana=(rank_anterior-Rank))

febrero_variaciones<- febrero_variaciones %>% summarise(titulo,
                                                        entradas_mes, entradas_first_semana, entradas_ult_semana, 
                                                        var_entradas_mensual, entradas_semama_anterio, 
                                                        var_pantallas_semana_previa, var_pantallas_mes, 
                                                        var_rank_mensual, var_rank_ult_semana)
febrero_variaciones<- febrero_variaciones %>% mutate(rank=1:nrow(febrero_variaciones))
#write.csv(febrero_variaciones, "febrero_variaciones.csv")



febrero_estrenos<- febrero %>% filter(Semana.Cartel==1)
febrero_estrenos<-febrero_estrenos %>% mutate(rank=1:nrow(febrero_estrenos))
#write.csv(febrero_estrenos,"febrero_estrenos.csv")
```

#MARZO 
```{r}
marzo1<- read.csv("C:/Users/LENOVO/Documents/GitHub/EYD/reporte-mensual-cine-argentina/marzo/1.MARZO_03_09.csv", sep=";")
marzo2<- read.csv("C:/Users/LENOVO/Documents/GitHub/EYD/reporte-mensual-cine-argentina/marzo/2.MARZO_10_16.csv", sep=";")
marzo3<- read.csv("C:/Users/LENOVO/Documents/GitHub/EYD/reporte-mensual-cine-argentina/marzo/3.MARZO_17_23.csv", sep=";")
marzo4<- read.csv("C:/Users/LENOVO/Documents/GitHub/EYD/reporte-mensual-cine-argentina/marzo/4.MARZO_24_30.csv", sep=";")

marzo<- bind_rows(marzo1,marzo2,marzo3,marzo4) %>% mutate(cantidad=1)
rm(list = c("marzo1","marzo2","marzo3","marzo4"))
```


```{r}
marzo_datos<- marzo %>%  group_by(Titulo) %>% summarise(entradas_mes=sum(Espec..Semana),      
                                                            entradas_ult_semana=last(Espec..Semana),
                                                            entradas_semama_anterio=lag(Espec..Semana), 
                                                            entradas_first_semana= first(Espec..Semana),
                                                            semanas_total=max(Semana.Cartel),
                                                            pantallas_max=max(Pantallas),
                                                            pantallas_mes=sum(Pantallas),
                                                            pantallas_ult_semana=last(Pantallas), 
                                                            pantallas_semana_anterior=lag(Pantallas), 
                                                            pantallas_first_semana=first(Pantallas),
                                                            semanas_mes=sum(cantidad),
                                                            pais, region,tipo,cantidad=1, mes="MARZO", ï..Rank,
                                                            rank_mes=first(ï..Rank),
                                                            rank_anterior=lag(ï..Rank))

marzo_datos<-marzo_datos %>% summarise_all(last) %>% arrange(desc(entradas_mes))
marzo_datos<- marzo_datos %>% mutate(rank_total= 1:nrow(marzo_datos))
#write.csv(marzo_datos, "marzo_datos.csv")


marzo_variaciones<- marzo_datos %>% mutate(
                      var_entradas_mensual=percent((entradas_ult_semana-entradas_first_semana)/entradas_first_semana),                                          
                      var_entradas_semana_previa=percent((entradas_ult_semana-entradas_semama_anterio)/entradas_semama_anterio),                                 
                      var_pantallas_mes=percent((pantallas_ult_semana-pantallas_first_semana)/pantallas_first_semana),
                      var_pantallas_semana_previa=percent((pantallas_ult_semana-pantallas_semana_anterior)/pantallas_semana_anterior), 
                      var_rank_mensual=(rank_mes-ï..Rank), 
                      var_rank_ult_semana=(rank_anterior-ï..Rank))

marzo_variaciones<- marzo_variaciones %>% summarise(Titulo,
                                                        entradas_mes, entradas_first_semana, entradas_ult_semana, 
                                                        var_entradas_mensual, entradas_semama_anterio, 
                                                        var_pantallas_semana_previa, var_pantallas_mes, 
                                                        var_rank_mensual, var_rank_ult_semana)
marzo_variaciones<- marzo_variaciones %>% mutate(rank=1:nrow(marzo_variaciones))
#write.csv(marzo_variaciones, "marzo_variaciones.csv")

```


